[workspace]
members = [
    "microwiki",
    
    "plugin",
    "ipc",

    "command_web",
    "command_add",
    "command_export",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
incremental = false