[package]
name = "web"
version = "0.1.0"
authors = ["CodeSteak <codesteak@shellf.art>"]
edition = "2018"

[dependencies]
ipc = { path = "../../../ipc" }
plugin = { path = "../../../plugin" }
actix-web = "0.7.18"
serde_json = "1.0"
serde = { version = "1.0" }

[profile.release]
lto = true
